 
[tool.pixi.project]
name = "learn-pydantic"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.dependencies]
jupyter = ">=1.0.0,<1.1"
ipykernel = ">=6.29.3,<6.30"
pydantic = ">=2.6.4,<2.7"
jupyterlab = ">=4.1.5,<4.2"
motor = ">=3.4.0,<3.5"
fastapi = ">=0.103.0,<0.104"
typing_extensions = ">=4.11.0,<4.12"

